"""add wins and defeats in user

Revision ID: 3329d2fa133f
Revises: 5d47bb896590
Create Date: 2023-11-29 19:53:05.091040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3329d2fa133f'
down_revision: Union[str, None] = '5d47bb896590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('defeats', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'defeats')
    op.drop_column('users', 'wins')
    # ### end Alembic commands ###
