"""add referals

Revision ID: 44ece4a17c64
Revises: 872cd72d2d2c
Create Date: 2023-12-09 14:33:35.361619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ece4a17c64'
down_revision: Union[str, None] = '872cd72d2d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'parent_ref_users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('telegram_id', sa.BigInteger(), nullable=True),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('token', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token'),
    )
    op.create_index(
        op.f('ix_parent_ref_users_telegram_id'),
        'parent_ref_users',
        ['telegram_id'],
        unique=True,
    )
    op.create_table(
        'linked_ref_users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('telegram_id', sa.BigInteger(), nullable=True),
        sa.Column('username', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['parent_id'],
            ['parent_ref_users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_linked_ref_users_telegram_id'),
        'linked_ref_users',
        ['telegram_id'],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_linked_ref_users_telegram_id'), table_name='linked_ref_users'
    )
    op.drop_table('linked_ref_users')
    op.drop_index(
        op.f('ix_parent_ref_users_telegram_id'), table_name='parent_ref_users'
    )
    op.drop_table('parent_ref_users')
    # ### end Alembic commands ###
